name: simple-worm-scripts

channels:
  - conda-forge
  - pytorch

dependencies:
  - python = 3.9
  - fenics = 2019.1.0
  - numpy = 1.26
  - matplotlib = 3.8.0
  - pytorch = 2.3.1
  - git
  - pip
  - pip:
      - git+https://gitlab.com/tom-ranner/simple-worm.git@master
