// This code conforms with the UFC specification version 2018.1.0
// and was automatically generated by FFC version 2019.1.0.
//
// This code was generated with the following parameters:
//

//  add_tabulate_tensor_timing:     False
//  convert_exceptions_to_warnings: False
//  cpp_optimize:                   True
//  cpp_optimize_flags:             '-O2'
//  epsilon:                        1e-14
//  error_control:                  False
//  external_include_dirs:          ['/opt/conda/include', '/opt/conda/include/eigen3'
//                                  , '/opt/conda/include']
//  external_includes:              ''
//  external_libraries:             ''
//  external_library_dirs:          ''
//  form_postfix:                   False
//  format:                         'ufc'
//  generate_dummy_tabulate_tensor: False
//  max_signature_length:           0
//  no-evaluate_basis_derivatives:  True
//  optimize:                       True
//  precision:                      None
//  quadrature_degree:              None
//  quadrature_rule:                None
//  representation:                 'auto'
//  split:                          False

#ifndef __FFC_COORDINATE_MAPPING_D3D86B312476C09A962A560CE7793FCB0BD40287_H
#define __FFC_COORDINATE_MAPPING_D3D86B312476C09A962A560CE7793FCB0BD40287_H
#include "ffc_element_06f4f8cdd292377f304b8bfc265c6ac65c33b070.h"
#include "ffc_element_2b921bb5283c41e0489f9c5fddeabe6ba6712798.h"
#include <algorithm>
#include <iostream>
#include <stdexcept>
#include <ufc.h>

class ffc_coordinate_mapping_d3d86b312476c09a962a560ce7793fcb0bd40287_coordinate_mapping_main: public ufc::coordinate_mapping
{
public:

  ffc_coordinate_mapping_d3d86b312476c09a962a560ce7793fcb0bd40287_coordinate_mapping_main();

  ~ffc_coordinate_mapping_d3d86b312476c09a962a560ce7793fcb0bd40287_coordinate_mapping_main() override;

  const char * signature() const final override;

  ufc::coordinate_mapping * create() const final override;

  std::size_t geometric_dimension() const final override;

  std::size_t topological_dimension() const final override;

  ufc::shape cell_shape() const final override;

  ufc::finite_element * create_coordinate_finite_element() const final override;

  ufc::dofmap * create_coordinate_dofmap() const final override;

  void compute_physical_coordinates(
      double * x, std::size_t num_points,
      const double * X,
      const double * coordinate_dofs) const final override;

  void compute_reference_coordinates(
      double * X, std::size_t num_points,
      const double * x,
      const double * coordinate_dofs, int cell_orientation) const final override;

  void compute_reference_geometry(
      double * X, double * J, double * detJ, double * K, std::size_t num_points,
      const double * x,
      const double * coordinate_dofs, int cell_orientation) const final override;

  void compute_jacobians(
      double * J, std::size_t num_points,
      const double * X,
      const double * coordinate_dofs) const final override;

  void compute_jacobian_determinants(
      double * detJ, std::size_t num_points,
      const double * J,
      int cell_orientation) const final override;

  void compute_jacobian_inverses(
      double * K, std::size_t num_points,
      const double * J, const double * detJ) const final override;

  void compute_geometry(
      double * x, double * J, double * detJ, double * K, std::size_t num_points,
      const double * X,
      const double * coordinate_dofs, int cell_orientation) const final override;

  void compute_midpoint_geometry(
      double * x, double * J,
      const double * coordinate_dofs) const final override;

};

extern "C" ufc::coordinate_mapping * create_ffc_coordinate_mapping_d3d86b312476c09a962a560ce7793fcb0bd40287_coordinate_mapping_main();

#endif
